// <auto-generated />
namespace Naive_bayes.Data_Access.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.3.0")]
    public sealed partial class addedallclassess : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addedallclassess));
        
        string IMigrationMetadata.Id
        {
            get { return "202002131752051_addedallclassess"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
